spring:
  application:
    name: inventario

  datasource:
    url: jdbc:mysql://localhost:3306/inventario_chatbot?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

security:
  jwt:
    secret-key: "cambia-esto-por-un-secreto-largo-y-seguro-1234567890"
    expiration-minutes: 60