spring:
  application:
    name: inventario

  datasource:
    url: jdbc:mysql://localhost:3306/inventario_chatbot?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

security:
  jwt:
    secret-key: "VmpzNGN5U21hVlFxZ2hRREhKZHc0ZmtlQnFRQTR0Yk9sOUVsb2c3Y2VvMUpjR1N1UWxKWFdDazUzYmdlM3Q4T1d0UXJ4UjJ0VmxHUnVjR29KcG9sQ1pYdkE5S2FhV3J4Y0hGZW5lVTRWdHdEalZlRzZ6Zk5rMWFh"
    expiration-minutes: 60